repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    -   id: check-case-conflict
    -   id: check-executables-have-shebangs
    -   id: check-yaml
    -   id: check-toml
    -   id: check-ast
    -   id: debug-statements
    -   id: check-docstring-first
    -   id: check-merge-conflict
    -   id: detect-private-key
    -   id: trailing-whitespace
    -   id: file-contents-sorter

-   repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
    rev: v1.0.5
    hooks:
    -   id: python-bandit-vulnerability-check
        language: python
        args: ["-lll", "--recursive", "./", '--skip', 'B605']
        files: .py$

-   repo: https://github.com/MarcoGorelli/absolufy-imports
    rev: v0.3.0
    hooks:
    -   id: absolufy-imports

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort


-   repo: https://github.com/PyCQA/autoflake
    rev: v1.7.7
    hooks:
    -   id: autoflake
        args: [
            "--in-place", "--remove-unused-variables", "--recursive",
            "--remove-all-unused-imports", ".",
        ]

-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: ''  # Use the sha / tag you want to point at
    hooks:
    -   id: autopep8
        args: [
            "--in-place",
            "--recursive",
        ]